### PR TITLE
Allow vector 0.13

### PR DESCRIPTION
**Pull request by felixonmars**
Builds fine and all tests pass.

### CODE REVIEW

**Comment by juhp** [comment]
Any chance of a Hackage revision first, please?

**Comment by andreasabel** [comment]
> Any chance of a Hackage revision first, please?

Here you go: https://hackage.haskell.org/package/cassava-megaparsec-2.0.4/revisions/

**Comment by cptrodolfox** [comment]
Thanks for the work @juhp, @felixonmars , and @andreasabel . I will be reviewing the changes on the upper version bound of vector, after the work on this PR https://github.com/stackbuilders/cassava-megaparsec/pull/25 is merged on the main branch.

**Review by cptrodolfox — APPROVED** [review]
Thanks for the update of the bound.

**Pull request merged**
