### PR TITLE
Allow megaparsec 9.0

### PR DESCRIPTION
**Pull request by CristhianMotoche**

### CODE REVIEW

**Review by juanpaucar — APPROVED** [review]
LGTM

**Comment by sestrella** [comment]
@CristhianMotoche looks good, although I wonder if you could share the results of compiling this library with `megaparsec` set to `==9.0.0` just to make sure it works properly.

**Comment by CristhianMotoche** [comment]
Hey @sestrella Sure. I used `stack` locally with the following `stack.yml`:
```yml
resolver: lts-16.13
extra-deps:
  - hspec-megaparsec-2.2.0
  - megaparsec-9.0.0
```
Also, I removed the previous precompiled packages of megaparsec, just in case.

The results were successful:
```
➜  cassava-megaparsec git:(chore/support-megaparsec-9.0) ✗ stack build --test
Stack has not been tested with GHC versions above 8.6, and using 8.8.4, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
colour              > using precompiled package
hashable            > using precompiled package
integer-logarithms  > using precompiled package
parser-combinators  > using precompiled package
Only                > configure
ansi-terminal       > using precompiled package
case-insensitive    > using precompiled package
primitive           > using precompiled package
random              > using precompiled package
scientific          > using precompiled package
attoparsec          > using precompiled package
Only                > Configuring Only-0.1...
Only                > build
clock               > configure
Only                > Preprocessing library for Only-0.1..
Only                > Building library for Only-0.1..
Only                > [1 of 1] Compiling Data.Tuple.Only
clock               > Configuring clock-0.8...
clock               > build
hspec-discover      > configure
clock               > Preprocessing library for clock-0.8..
clock               > Building library for clock-0.8..
clock               > [1 of 1] Compiling System.Clock
Only                > copy/register
Only                > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/Only-0.1-IJIAET7WRoQFFeBfrGSvp2
hspec-discover      > Configuring hspec-discover-2.7.4...
Only                > Registering library for Only-0.1..
hspec-discover      > build
call-stack          > configure
hspec-discover      > Preprocessing library for hspec-discover-2.7.4..
hspec-discover      > Building library for hspec-discover-2.7.4..
hspec-discover      > [1 of 4] Compiling Paths_hspec_discover
hspec-discover      > [2 of 4] Compiling Test.Hspec.Discover.Config
call-stack          > Configuring call-stack-0.2.0...
hspec-discover      > [3 of 4] Compiling Test.Hspec.Discover.Sort
call-stack          > build
setenv              > configure
call-stack          > Preprocessing library for call-stack-0.2.0..
call-stack          > Building library for call-stack-0.2.0..
call-stack          > [1 of 3] Compiling Data.SrcLoc
call-stack          > [2 of 3] Compiling Data.CallStack
call-stack          > [3 of 3] Compiling Paths_call_stack
hspec-discover      > [4 of 4] Compiling Test.Hspec.Discover.Run
setenv              > Configuring setenv-0.1.1.3...
setenv              > build
text-short          > configure
call-stack          > copy/register
setenv              > Preprocessing library for setenv-0.1.1.3..
setenv              > Building library for setenv-0.1.1.3..
call-stack          > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/call-stack-0.2.0-60bTmb9VEHP3C0mVwwOjhh
setenv              > [1 of 1] Compiling System.SetEnv
call-stack          > Registering library for call-stack-0.2.0..
clock               > copy/register
clock               > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/clock-0.8-BDr0ZJKaVWEAskyGHHBCXi
hspec-discover      > Preprocessing executable 'hspec-discover' for hspec-discover-2.7.4..
hspec-discover      > Building executable 'hspec-discover' for hspec-discover-2.7.4..
clock               > Registering library for clock-0.8..
text-short          > Configuring text-short-0.1.3...
setenv              > copy/register
hspec-discover      > [1 of 2] Compiling Main
unordered-containers> using precompiled package
setenv              > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/setenv-0.1.1.3-AApHapTZwGVKX9z2HargZZ
hspec-discover      > [2 of 2] Compiling Paths_hspec_discover
text-short          > build
splitmix            > configure
setenv              > Registering library for setenv-0.1.1.3..
text-short          > Preprocessing library for text-short-0.1.3..
text-short          > Building library for text-short-0.1.3..
vector              > using precompiled package
text-short          > [1 of 5] Compiling PrimOps
hspec-discover      > Linking .stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build/hspec-discover/hspec-discover ...
text-short          > [2 of 5] Compiling Data.Text.Short.Internal
splitmix            > Configuring splitmix-0.0.5...
splitmix            > build
megaparsec          > configure
splitmix            > Preprocessing library for splitmix-0.0.5..
splitmix            > Building library for splitmix-0.0.5..
hspec-discover      > copy/register
hspec-discover      > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/hspec-discover-2.7.4-AHgBVDrV63MEfiScSkrmY3
splitmix            > [1 of 3] Compiling Data.Bits.Compat
hspec-discover      > Installing executable hspec-discover in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/bin
splitmix            > [2 of 3] Compiling System.Random.SplitMix
hspec-discover      > Registering library for hspec-discover-2.7.4..
megaparsec          > Configuring megaparsec-9.0.0...
megaparsec          > build
tf-random           > configure
megaparsec          > Preprocessing library for megaparsec-9.0.0..
megaparsec          > Building library for megaparsec-9.0.0..
splitmix            > [3 of 3] Compiling System.Random.SplitMix32
megaparsec          > [ 1 of 16] Compiling Text.Megaparsec.Error[boot]
megaparsec          > [ 2 of 16] Compiling Text.Megaparsec.Pos
tf-random           > Configuring tf-random-0.5...
tf-random           > build
HUnit               > configure
tf-random           > Preprocessing library for tf-random-0.5..
tf-random           > Building library for tf-random-0.5..
tf-random           > [1 of 4] Compiling System.Random.TF.Gen
splitmix            > copy/register
splitmix            > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/splitmix-0.0.5-inm33kruRIL3MoAEVOOwx
splitmix            > Registering library for splitmix-0.0.5..
HUnit               > Configuring HUnit-1.6.0.0...
HUnit               > build
QuickCheck          > configure
HUnit               > Preprocessing library for HUnit-1.6.0.0..
HUnit               > Building library for HUnit-1.6.0.0..
HUnit               > [1 of 6] Compiling Paths_HUnit
megaparsec          > [ 3 of 16] Compiling Text.Megaparsec.State
text-short          > [3 of 5] Compiling Data.Text.Short.Unsafe
text-short          > [4 of 5] Compiling Data.Text.Short
HUnit               > [2 of 6] Compiling Test.HUnit.Lang
text-short          > [5 of 5] Compiling Data.Text.Short.Partial
QuickCheck          > Configuring QuickCheck-2.13.2...
QuickCheck          > build
QuickCheck          > Preprocessing library for QuickCheck-2.13.2..
QuickCheck          > Building library for QuickCheck-2.13.2..
HUnit               > [3 of 6] Compiling Test.HUnit.Base
tf-random           > [2 of 4] Compiling System.Random.TF.Init
tf-random           >
tf-random           > /tmp/stack28875/tf-random-0.5/src/System/Random/TF/Init.hs:94:5: warning: [-Wdeprecations]
tf-random           >     In the use of ‘bitSize’ (imported from Data.Bits):
tf-random           >     Deprecated: "Use 'bitSizeMaybe' or 'finiteBitSize' instead"
tf-random           >    |
tf-random           > 94 |   | bitSize n > 64 = error "mkTFGen: case where size of Int > 64 not implemented"
tf-random           >    |     ^^^^^^^
QuickCheck          > [ 1 of 16] Compiling Test.QuickCheck.Exception
tf-random           > [3 of 4] Compiling System.Random.TF
tf-random           > [4 of 4] Compiling System.Random.TF.Instances
QuickCheck          > [ 2 of 16] Compiling Test.QuickCheck.Random
megaparsec          > [ 4 of 16] Compiling Text.Megaparsec.Stream
text-short          > copy/register
text-short          > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/text-short-0.1.3-8waCp3fCpXRIa99JlYS0EC
QuickCheck          > [ 3 of 16] Compiling Test.QuickCheck.Gen
text-short          > Registering library for text-short-0.1.3..
cassava             > configure
HUnit               > [4 of 6] Compiling Test.HUnit.Terminal
HUnit               > [5 of 6] Compiling Test.HUnit.Text
HUnit               > [6 of 6] Compiling Test.HUnit
cassava             > Configuring cassava-0.5.2.0...
cassava             > build
cassava             > Preprocessing library for cassava-0.5.2.0..
cassava             > Building library for cassava-0.5.2.0..
HUnit               > copy/register
HUnit               > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/HUnit-1.6.0.0-Jclpnuqehp8GGyrAnfCVLK
QuickCheck          > [ 4 of 16] Compiling Test.QuickCheck.Gen.Unsafe
QuickCheck          > [ 5 of 16] Compiling Test.QuickCheck.Arbitrary
cassava             > [ 1 of 10] Compiling Data.Csv.Types
HUnit               > Registering library for HUnit-1.6.0.0..
hspec-expectations  > configure
tf-random           >
tf-random           > copy/register
tf-random           > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/tf-random-0.5-9HF06zWGTuQIFpJn5Dfvt0
tf-random           > Registering library for tf-random-0.5..
cassava             > [ 2 of 10] Compiling Data.Csv.Util
hspec-expectations  > Configuring hspec-expectations-0.8.2...
hspec-expectations  > build
hspec-expectations  > Preprocessing library for hspec-expectations-0.8.2..
hspec-expectations  > Building library for hspec-expectations-0.8.2..
megaparsec          > [ 5 of 16] Compiling Text.Megaparsec.Error
cassava             > [ 3 of 10] Compiling Data.Csv.Parser
hspec-expectations  > [1 of 4] Compiling Paths_hspec_expectations
hspec-expectations  > [2 of 4] Compiling Test.Hspec.Expectations.Contrib
hspec-expectations  > [3 of 4] Compiling Test.Hspec.Expectations.Matcher
hspec-expectations  > [4 of 4] Compiling Test.Hspec.Expectations
hspec-expectations  > copy/register
hspec-expectations  > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/hspec-expectations-0.8.2-Gyxpw5RZvqV2WiQLfU4YHY
hspec-expectations  > Registering library for hspec-expectations-0.8.2..
megaparsec          > [ 6 of 16] Compiling Text.Megaparsec.Error.Builder
cassava             > [ 4 of 10] Compiling Data.Csv.Conversion.Internal
megaparsec          > [ 7 of 16] Compiling Text.Megaparsec.Class
megaparsec          > [ 8 of 16] Compiling Text.Megaparsec.Internal
QuickCheck          > [ 6 of 16] Compiling Test.QuickCheck.Poly
QuickCheck          > [ 7 of 16] Compiling Test.QuickCheck.Modifiers
cassava             > [ 5 of 10] Compiling Data.Csv.Conversion
megaparsec          > [ 9 of 16] Compiling Text.Megaparsec.Debug
megaparsec          > [10 of 16] Compiling Text.Megaparsec
megaparsec          > [11 of 16] Compiling Text.Megaparsec.Common
megaparsec          > [12 of 16] Compiling Text.Megaparsec.Lexer
megaparsec          > [13 of 16] Compiling Text.Megaparsec.Char
megaparsec          > [14 of 16] Compiling Text.Megaparsec.Char.Lexer
QuickCheck          > [ 8 of 16] Compiling Test.QuickCheck.Function
megaparsec          > [15 of 16] Compiling Text.Megaparsec.Byte
megaparsec          > [16 of 16] Compiling Text.Megaparsec.Byte.Lexer
QuickCheck          > [ 9 of 16] Compiling Test.QuickCheck.Text
QuickCheck          > [10 of 16] Compiling Test.QuickCheck.State
QuickCheck          > [11 of 16] Compiling Test.QuickCheck.Property
megaparsec          > copy/register
megaparsec          > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/megaparsec-9.0.0-G6ue58gDjgS76taxp956RJ
megaparsec          > Registering library for megaparsec-9.0.0..
hspec-megaparsec    > configure
hspec-megaparsec    > Configuring hspec-megaparsec-2.2.0...
hspec-megaparsec    > build
hspec-megaparsec    > Preprocessing library for hspec-megaparsec-2.2.0..
hspec-megaparsec    > Building library for hspec-megaparsec-2.2.0..
hspec-megaparsec    > [1 of 1] Compiling Test.Hspec.Megaparsec
QuickCheck          > [12 of 16] Compiling Test.QuickCheck.Test
hspec-megaparsec    > copy/register
hspec-megaparsec    > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/hspec-megaparsec-2.2.0-BqIqFJRxEIpE2qaFxpM1eG
hspec-megaparsec    > Registering library for hspec-megaparsec-2.2.0..
cassava             > [ 6 of 10] Compiling Data.Csv.Encoding
QuickCheck          > [13 of 16] Compiling Test.QuickCheck.Monadic
QuickCheck          > [14 of 16] Compiling Test.QuickCheck.All
QuickCheck          > [15 of 16] Compiling Test.QuickCheck.Features
QuickCheck          > [16 of 16] Compiling Test.QuickCheck
QuickCheck          > copy/register
QuickCheck          > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/QuickCheck-2.13.2-DaUcgEOc05f2iBoF7dUZuu
QuickCheck          > Registering library for QuickCheck-2.13.2..
quickcheck-io       > configure
quickcheck-io       > Configuring quickcheck-io-0.2.0...
quickcheck-io       > build
quickcheck-io       > Preprocessing library for quickcheck-io-0.2.0..
quickcheck-io       > Building library for quickcheck-io-0.2.0..
quickcheck-io       > [1 of 2] Compiling Paths_quickcheck_io
quickcheck-io       > [2 of 2] Compiling Test.QuickCheck.IO
quickcheck-io       > copy/register
quickcheck-io       > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/quickcheck-io-0.2.0-Nkq1HnyA3Q6KM7hHwP3NX
quickcheck-io       > Registering library for quickcheck-io-0.2.0..
hspec-core          > configure
hspec-core          > Configuring hspec-core-2.7.4...
hspec-core          > build
hspec-core          > Preprocessing library for hspec-core-2.7.4..
hspec-core          > Building library for hspec-core-2.7.4..
hspec-core          > [ 1 of 28] Compiling Control.Concurrent.Async
cassava             > [ 7 of 10] Compiling Data.Csv.Incremental
hspec-core          > [ 2 of 28] Compiling Data.Algorithm.Diff
hspec-core          > [ 3 of 28] Compiling Paths_hspec_core
hspec-core          > [ 4 of 28] Compiling Test.Hspec.Core.Clock
hspec-core          > [ 5 of 28] Compiling Test.Hspec.Core.Compat
hspec-core          > [ 6 of 28] Compiling Test.Hspec.Core.Example.Location
hspec-core          > [ 7 of 28] Compiling Test.Hspec.Core.Formatters.Diff
hspec-core          > [ 8 of 28] Compiling Test.Hspec.Core.Formatters.Free
hspec-core          > [ 9 of 28] Compiling Test.Hspec.Core.Timer
hspec-core          > [10 of 28] Compiling Test.Hspec.Core.Util
hspec-core          > [11 of 28] Compiling Test.Hspec.Core.QuickCheckUtil
cassava             > [ 8 of 10] Compiling Data.Csv.Streaming
hspec-core          > [12 of 28] Compiling Test.Hspec.Core.Example
cassava             > [ 9 of 10] Compiling Data.Csv.Builder
hspec-core          > [13 of 28] Compiling Test.Hspec.Core.Tree
cassava             > [10 of 10] Compiling Data.Csv
cassava             > copy/register
hspec-core          > [14 of 28] Compiling Test.Hspec.Core.Shuffle
cassava             > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/cassava-0.5.2.0-EImueLfvz3TE91ReMBsKWn
hspec-core          > [15 of 28] Compiling Test.Hspec.Core.Spec.Monad
cassava             > Registering library for cassava-0.5.2.0..
hspec-core          > [16 of 28] Compiling Test.Hspec.Core.Hooks
hspec-core          > [17 of 28] Compiling Test.Hspec.Core.Spec
hspec-core          > [18 of 28] Compiling Test.Hspec.Core.QuickCheck
hspec-core          > [19 of 28] Compiling Test.Hspec.Core.Formatters.Monad
hspec-core          > [20 of 28] Compiling Test.Hspec.Core.Formatters
hspec-core          > [21 of 28] Compiling Test.Hspec.Core.Format
hspec-core          > [22 of 28] Compiling Test.Hspec.Core.Runner.Eval
hspec-core          > [23 of 28] Compiling Test.Hspec.Core.Formatters.Internal
hspec-core          > [24 of 28] Compiling Test.Hspec.Core.Config.Util
hspec-core          > [25 of 28] Compiling Test.Hspec.Core.Config.Options
hspec-core          > [26 of 28] Compiling Test.Hspec.Core.FailureReport
hspec-core          > [27 of 28] Compiling Test.Hspec.Core.Config
hspec-core          > [28 of 28] Compiling Test.Hspec.Core.Runner
hspec-core          > copy/register
hspec-core          > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/hspec-core-2.7.4-2BKYh5636SiKwvTOw2aqip
hspec-core          > Registering library for hspec-core-2.7.4..
hspec               > configure
hspec               > Configuring hspec-2.7.4...
hspec               > build
hspec               > Preprocessing library for hspec-2.7.4..
hspec               > Building library for hspec-2.7.4..
hspec               > [1 of 6] Compiling Paths_hspec
hspec               > [2 of 6] Compiling Test.Hspec.Formatters
hspec               > [3 of 6] Compiling Test.Hspec.Discover
hspec               > [4 of 6] Compiling Test.Hspec.Runner
hspec               > [5 of 6] Compiling Test.Hspec
hspec               > [6 of 6] Compiling Test.Hspec.QuickCheck
hspec               > copy/register
hspec               > Installing library in /home/cmotoche/.stack/snapshots/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/hspec-2.7.4-E5grpVK0ITwJfKdBzkHx1C
hspec               > Registering library for hspec-2.7.4..
cassava-megaparsec  > build (lib + test)
Preprocessing library for cassava-megaparsec-2.0.2..
Building library for cassava-megaparsec-2.0.2..
[1 of 1] Compiling Data.Csv.Parser.Megaparsec
Preprocessing test suite 'tests' for cassava-megaparsec-2.0.2..
Building test suite 'tests' for cassava-megaparsec-2.0.2..
[1 of 1] Compiling Main
Linking .stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build/tests/tests ...
cassava-megaparsec  > copy/register
Installing library in /home/cmotoche/Documents/SB/cassava-megaparsec/.stack-work/install/x86_64-linux/5a9d535cdb488cc9d5d81d59bb555d0feadd146edd770d600fa5aed0b94b8412/8.8.4/lib/x86_64-linux-ghc-8.8.4/cassava-megaparsec-2.0.2-DPHye72e1meIgoBcpBuA1z
Registering library for cassava-megaparsec-2.0.2..
cassava-megaparsec  > test (suite: tests)

Progress 30/31: cassava-megaparsec
decode
  decodes simple data
  decodes simple data skipping header
  handles CRLF sequence correctly
  handles missing end of line
  parses the empty line all right
  handles leading space
  parses the RFC 4180 test data correctly
decodeWith
  using tab as delimiter
    works fine with tab as delimiter
    handles CRLF sequence correctly
    handles missing end of line
    parses the empty line all right
    handles leading space
decodeByName
  decodes simple data
  decodes entries with two fields
  decodes header ending with CRLF
  decodes data with training CRLF
  decodes multiply entries (CRLF separated)
decodeByNameWith
  using tab as delimiter
    decodes simple data
    decodes entries with two fields
    decodes header ending with CRLF
    decodes data with training CRLF
    decodes multiply entries (CRLF separated)

Finished in 0.0008 seconds
22 examples, 0 failures

cassava-megaparsec  > Test suite tests passed
Completed 31 action(s).
➜
```

**Review by sestrella — APPROVED** [review]
@CristhianMotoche awesome, thank you for sharing the output

**Pull request merged**
